[package]
name = "afx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
egui_glow = "0.19.0"
rfd = "0.10.0"
rodio = { version = "0.16.0", features = ["symphonia-all"] }
